<a href="https://colab.research.google.com/github/adasko-a/datascience_bootcamp/blob/main/01_wprowadzenie/pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
pd.__version__

'2.2.2'

In [3]:
import numpy as np

# Tworzenie obiektów

# Series

In [5]:
s = pd.Series(data=[3,4,5])
s

0    3
1    4
2    5
dtype: int64

In [6]:
pd.Series(data=[3.0,4.0,5.0], index=['a','b','c'])

a    3.0
b    4.0
c    5.0
dtype: float64

In [7]:
pd.Series(data=[3,4,5,np.nan])

0    3.0
1    4.0
2    5.0
3    NaN
dtype: float64

In [8]:
pd.Series(data=[True,False,True])

0     True
1    False
2     True
dtype: bool

In [26]:
s=pd.Series(data=np.arange(20),index=pd.date_range(start='20260301',periods=20))

In [21]:
s.index

DatetimeIndex(['2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04',
               '2026-03-05', '2026-03-06', '2026-03-07', '2026-03-08',
               '2026-03-09', '2026-03-10', '2026-03-11', '2026-03-12',
               '2026-03-13', '2026-03-14', '2026-03-15', '2026-03-16',
               '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
              dtype='datetime64[ns]', freq='D')

In [23]:
s = pd.Series(data=['java','python','cpp','ruby','sql'],name='langs')
s

0      java
1    python
2       cpp
3      ruby
4       sql
Name: langs, dtype: object

In [15]:
type(s)

pandas.core.series.Series

In [28]:
s.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
s.dtypes

dtype('int64')

In [30]:
s.shape

(20,)

In [31]:
price=pd.Series(data={'Apple':200,'CD Projekt':60,'Amazon':1900,'KGHM':np.nan})
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [33]:
price.index

Index(['Apple', 'CD Projekt', 'Amazon', 'KGHM'], dtype='object')

In [34]:
price['CD Projekt']

np.float64(60.0)

In [35]:
price[1]

/tmp/ipykernel_303/4074423798.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  price[1]

np.float64(60.0)

In [38]:
price.count()

In [42]:
price.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [40]:
[price.max(),price.min(),price.std()]

[1900.0, 60.0, 1024.3046421841502]

In [41]:
price.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [44]:
price.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [45]:
price.nsmallest(2)

CD Projekt     60.0
Apple         200.0
dtype: float64

In [49]:
price.rank()

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [47]:
price.sort_values()

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [50]:
price.apply(lambda x: 3.8*x)

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

# DataFrame

In [51]:
df = pd.DataFrame(data=[12,12,32])
df

    0
0  12
1  12
2  32

In [52]:
df = pd.DataFrame(data=[12,12,32],index=['first','second','third'],columns=['col_1'])
df

        col_1
first      12
second     12
third      32

In [56]:
df = pd.DataFrame(data={'WIG20':['PKN ORLEN','PKO BP'],
                      'mWIG40':['Amica','Playway']},index=['first','second'])
df

            WIG20   mWIG40
first   PKN ORLEN    Amica
second     PKO BP  Playway

In [57]:
[df.columns,df.index,df.values]

[Index(['WIG20', 'mWIG40'], dtype='object'),
 Index(['first', 'second'], dtype='object'),
 array([['PKN ORLEN', 'Amica'],
        ['PKO BP', 'Playway']], dtype=object)]

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   WIG20   2 non-null      object
 1   mWIG40  2 non-null      object
dtypes: object(2)
memory usage: 156.0+ bytes

In [59]:
df.describe()

            WIG20 mWIG40
count           2      2
unique          2      2
top     PKN ORLEN  Amica
freq            1      1

#df-selekcja kolumn

In [60]:
df

            WIG20   mWIG40
first   PKN ORLEN    Amica
second     PKO BP  Playway

In [62]:
df['WIG20']

(first     PKN ORLEN
 second       PKO BP
 Name: WIG20, dtype: object,
 pandas.core.frame.DataFrame)

In [64]:
type(df['WIG20'])

pandas.core.series.Series

In [65]:
df[['WIG20']]

            WIG20
first   PKN ORLEN
second     PKO BP

In [66]:
type(df[['WIG20']])

pandas.core.frame.DataFrame

In [67]:
df.columns=['a','b']
df

                a        b
first   PKN ORLEN    Amica
second     PKO BP  Playway

In [68]:
df.a

first     PKN ORLEN
second       PKO BP
Name: a, dtype: object

In [70]:
df['c'] = df.a +'_'+ df.b
df

                a        b                c
first   PKN ORLEN    Amica  PKN ORLEN_Amica
second     PKO BP  Playway   PKO BP_Playway

In [73]:
df = pd.DataFrame(data=[[12,12,32],[12,23,45],[54,54,66]],index=['first','second','third'],columns=['col_1','col_2','col_3'])
df

        col_1  col_2  col_3
first      12     12     32
second     12     23     45
third      54     54     66

In [75]:
df.loc['first']

col_1    12
col_2    12
col_3    32
Name: first, dtype: int64

In [76]:
type(df.loc['first'])

pandas.core.series.Series

In [77]:
df.iloc[0]

col_1    12
col_2    12
col_3    32
Name: first, dtype: int64

In [78]:
df.loc[:,'col_3']

first     32
second    45
third     66
Name: col_3, dtype: int64